spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:32768/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    platform: POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  output:
    ansi:
      enabled: always
  application:
    name: person-service
server:
  port: 8082